[package]
name = "tb6612fng"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"

description = "A `no_std` driver for the TB6612FNG motor driver."
repository = "https://github.com/rursprung/tb6612fng-rs"
categories = ["embedded", "hardware-support", "no-std"]
keywords = ["tb6612fng", "driver", "motor", "dc motor", "controller"]
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal = "0.2"

defmt = { version = "0.3", optional = true }

[dev-dependencies]
embedded-hal-mock = "0.9"
