[package]
name = "tb6612fng"
version = "0.1.0"
edition = "2021"

description = "A `no_std` driver for the TB6612FNG motor driver."
repository = "https://github.com/rursprung/tb6612fng-rs"
keywords = ["tb6612fng", "embedded", "driver", "no_std", "motor", "dc motor", "controller"]

[dependencies]
embedded-hal = "0.2"

defmt = { version = "0.3", optional = true }

[dev-dependencies]
embedded-hal-mock = { git = "https://github.com/rursprung/embedded-hal-mock.git", branch = "add-pwmpin-mock" }
